version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: blog_api_dev
    command: uvicorn main:application_factory --workers 1 --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - ./web/:/usr/src/
    env_file:
      - .env

  mongodb:
    image: mongo:7.0.7
    restart: on-failure
    container_name: blog_mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_log:/var/log/mongodb
      - ./mongo-entrypoint/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  redis:
    image: redis:6-alpine
    container_name: blog_redis_dev
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
    driver: local
    name: blog_mongodb_data_dev
  mongodb_log:
    driver: local
    name: blog_mongodb_log_dev
  redis_data:
    name: blog_redis_dev
